# #인포테이블 #리뷰테이블 #데이터전처리

In [1]:
import pandas as pd

In [3]:
# 인포 테이블
info = pd.read_csv('./google_maps_info_jongro.csv')
# 리뷰 테이블
review = pd.read_csv('./google_maps_review_jongro.csv')

In [106]:
# 괄호, 괄호 없애기
info['review'] = info['review'].str.replace('(','').str.replace(')','').str.replace(',','')

In [107]:
# 종로구를 포함하지 않는 가게 삭제
con1 = ~info['adress'].str.contains('종로구')
info.drop(info[con1].index, inplace=True)

In [108]:
# 리뷰, 평점 점수 없는 건 삭제
con2 = info['rating'].str.contains('정보없음')
con3 = info['review'].str.contains('정보없음')
info = info.loc[~con2|~con3]

In [111]:
# 중복 가게 하나로 합치기 진행 중
con4 = (info['name'] == '솔트24')
info[con4]

    name rating review category              adress
3   솔트24    4.5    110      제과점  서울특별시 종로구 율곡로3길 75
37  솔트24    4.4     94  프랑스 제과점  서울특별시 종로구 율곡로3길 75

In [112]:
info.loc[3] = ['솔트24 북촌점', '4.5', '204', '제과점', '서울특별시 종로구 율곡로3길 75']
info.loc[53, 'name'] = '솔트24 성대점'
info.loc[74, 'name'] = '솔트24 혜화본점'
info = info.loc[info.index != 37] # info = info.drop(info.index[35]) 리셋시키고 해야됨.

In [121]:
info[info['name'].str.contains('솔트')]

         name  rating  review category                      adress
3    솔트24 북촌점     4.5     204      제과점          서울특별시 종로구 율곡로3길 75
49   솔트24 성대점     4.1      11      제과점  서울특별시 종로구 창경궁로 236 이화빌딩 1층
66  솔트24 혜화본점     5.0       5      제과점         서울특별시 종로구 동숭길 36 1층

In [117]:
# 인덱스 리셋
info.reset_index(drop=True, inplace=True)

In [122]:
# 중복된 가게명이 있나요?
info['name'].value_counts()

name
파머스반브레드          1
밀토스트             1
베커린 안국점          1
스코프 서촌점          1
자미당 통인점          1
                ..
아티장 크로아상         1
모자이크 베이커리 북촌점    1
하이버              1
빅토리아베이커리 서촌      1
부암동와플            1
Name: count, Length: 101, dtype: int64

In [119]:
# 수치형 변환
info['rating'] = info['rating'].astype(float)
info['review'] = info['review'].astype(int)

In [123]:
info.info() # 솔트 처리 전까지 102개의 가게가 있었다. -1개

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      101 non-null    object
 1   rating    101 non-null    float64
 2   review    101 non-null    int32
 3   category  101 non-null    object
 4   adress    101 non-null    object
dtypes: float64(1), int32(1), object(3)
memory usage: 3.7+ KB

In [132]:
info.loc[36, 'adress'] = '서울특별시 종로구 자하문로7길 68-3'
info.loc[47, 'adress'] = '서울특별시 종로구 종로 333 상가 1층'
info.loc[48, 'adress'] = '서울특별시 종로구 필운대로 44 1층'
info.loc[67, 'adress'] = '서울특별시 종로구 사직동 9번지 301동 B122호'
info.loc[68, 'adress'] = '서울특별시 종로구 창신동 142-2번지 3호 지상 1층'
info.loc[77, 'adress'] = '서울특별시 종로구 부암동 185-4 1층'
info.loc[100, 'adress'] = '서울특별시 종로구 부암동 254-1번지 지상1층'

In [133]:
info[~info['adress'].str.startswith('서울특별시')]

Empty DataFrame
Columns: [name, rating, review, category, adress]
Index: []

In [137]:
info.loc[(36,47,48,67,68,77,100),:]

           name  rating  review category                          adress
36        마사마드레     4.4      14      제과점           서울특별시 종로구 자하문로7길 68-3
47   크로도(crodo)     5.0       4      제과점          서울특별시 종로구 종로 333 상가 1층
48          소금소     5.0       1      제과점            서울특별시 종로구 필운대로 44 1층
67          플레인     4.4       5      제과점    서울특별시 종로구 사직동 9번지 301동 B122호
68       맛나베이커리     5.0       1      제과점  서울특별시 종로구 창신동 142-2번지 3호 지상 1층
77          라프라     4.9      13  프랑스 제과점          서울특별시 종로구 부암동 185-4 1층
100       부암동와플     4.3      21      제과점      서울특별시 종로구 부암동 254-1번지 지상1층

In [139]:
info.loc[35, 'name'] = '파리바게뜨카페 광화문점'
info.loc[98, 'name'] = '요거트맨 종로서적점'

In [140]:
info[info['name'].str.endswith('점')]

             name  rating  review category                      adress
1        뚜레쥬르 종로점     4.2      56      제과점             서울특별시 종로구 종로 62
3        솔트24 북촌점     4.5     204      제과점          서울특별시 종로구 율곡로3길 75
20     우즈베이커리 익선점     4.1      82      제과점       서울특별시 종로구 돈화문로11나길 31
27      황금똥빵 종로본점     4.5       2      제과점            서울특별시 종로구 대학로 19
30  모자이크 베이커리 북촌점     4.9      47      제과점           서울특별시 종로구 북촌로4길 8
33      데코르 종로타워점     5.0       2      제과점             서울특별시 종로구 종로 51
34      스코프 서촌2호점     4.1      11      제과점            서울특별시 종로구 통인동 69
35   파리바게뜨카페 광화문점     4.0      80      제과점           서울특별시 종로구 당주동 100
42  모자이크 베이커리 율곡점     4.9      14      제과점        서울특별시 종로구 율곡로 221-12
44    파리바게트 종로구기점     4.2      24      제과점    서울특별시 종로구 진흥로22길 3 구기방아간
49       솔트24 성대점     4.1      11      제과점  서울특별시 종로구 창경궁로 236 이화빌딩 1층
52     파리바게뜨 청와대점     3.5      19      제과점          서울특별시 종로구 신교동 58-1
63   아티제 종로그랑서울2점     3.7       9       카페         서울특별시 종로구 청진동 종로 33
65    뚜레쥬르 카페대학로점     4.2      68      제과점             서울특별시 종로구 대명길 9
66      솔트24 혜화본점     5.0       5      제과점         서울특별시 종로구 동숭길 36 1층
72        자미당 통인점     4.3       4      제과점         서울특별시 종로구 자하문로7길 78
73        스코프 서촌점     4.4     446       카페    서울특별시 종로구 누하동 필운대로5가길 31
74        베커린 안국점     4.7       3       카페           서울특별시 종로구 윤보선길 20
85  서울은마꽈배기 경복궁역점     4.0       5      제과점            서울특별시 종로구 통의동 52
89   포제 종로센트로폴리스점     4.5      84       카페       서울특별시 종로구 공평동 우정국로 26
93      서울커피 익선본점     4.0     449       카페        서울특별시 종로구 익선동 166-31
96        어텐디 북촌점     4.3      10       카페          서울특별시 종로구 북촌로4길 16
98     요거트맨 종로서적점     4.6      10  디저트 전문점             서울특별시 종로구 종로 51

# 리뷰 테이블

In [179]:
review

         name                                             review
0     파머스반브레드  정말 맛있는 유럽빵. 아몬드 크로아상 정말 맛있어요! 아몬드 페이스트가 가득 들어있...
1     파머스반브레드  독일보다 나은 서울의 비트 베이커리, 버터가 들어간 브레첼은 꼭 먹어보세요, 꼭 먹...
2     파머스반브레드  이 곳 빵은 좋은 제품들로 만들어져서 비싸지만 정말 그 값을 합니다! 많이 먹어도 ...
3     파머스반브레드  훌륭한 음료 선택, 차분한 분위기. 케이크 선택이 하이라이트입니다. 인테리어도 너무...
4     파머스반브레드                           구수하고 속이 편안했던 시금치 치아바타 👍…
...       ...                                                ...
7489  빠다롤뺑프랑스                                      비싸지만 맛있오! 🤗🤗…
7490  빠다롤뺑프랑스      공간이 협소한 편이고 식탁도 있지만 자리가 10개 남짓인데 빵이 정말 맛있습니다.
7491  빠다롤뺑프랑스                     맛남. 가격은 조금 비싸지만 또 먹고싶은 빵이 있는곳.
7492  빠다롤뺑프랑스                       2016.11. 친절하고 싼 가격...그러나....
7493  빠다롤뺑프랑스                          딸기튀김빵과 마늘빵튀김은 맛있지만 빵이 비싸요

[7494 rows x 2 columns]

In [176]:
review['review'] = review['review'].str.replace('\n', " ")

In [177]:
review[review['review'].str.contains('\n')]

Empty DataFrame
Columns: [name, review]
Index: []

# merge table

In [187]:
merged = pd.merge(info, review, on="name", how="inner")
merged

,name,rating,review_x,category,adress,review_y
0,파머스반브레드,5.0,14,제과점,서울특별시 종로구 돈화문로11가길 59 현대뜨레비앙 111호,정말 맛있는 유럽빵. 아몬드 크로아상 정말 맛있어요! 아몬드 페이스트가 가득 들어있...
1,파머스반브레드,5.0,14,제과점,서울특별시 종로구 돈화문로11가길 59 현대뜨레비앙 111호,"독일보다 나은 서울의 비트 베이커리, 버터가 들어간 브레첼은 꼭 먹어보세요, 꼭 먹..."
2,파머스반브레드,5.0,14,제과점,서울특별시 종로구 돈화문로11가길 59 현대뜨레비앙 111호,이 곳 빵은 좋은 제품들로 만들어져서 비싸지만 정말 그 값을 합니다! 많이 먹어도 ...
3,파머스반브레드,5.0,14,제과점,서울특별시 종로구 돈화문로11가길 59 현대뜨레비앙 111호,"훌륭한 음료 선택, 차분한 분위기. 케이크 선택이 하이라이트입니다. 인테리어도 너무..."
4,파머스반브레드,5.0,14,제과점,서울특별시 종로구 돈화문로11가길 59 현대뜨레비앙 111호,구수하고 속이 편안했던 시금치 치아바타 👍…
...,...,...,...,...,...,...
5754,부암동와플,4.3,21,제과점,서울특별시 종로구 부암동 254-1번지 지상1층,부암동오면 이집 와플이 생각나네요^*^ 갠적으로 덕수궁옆 와플집에 뒤지지 않는 맛!!!
5755,부암동와플,4.3,21,제과점,서울특별시 종로구 부암동 254-1번지 지상1층,이 좋은 디저트 카페를 놓치지 마세요. 맛있지만 오히려 저렴한 품목을 제공합니다.
5756,부암동와플,4.3,21,제과점,서울특별시 종로구 부암동 254-1번지 지상1층,플레인 담백하고 맛있었음.
5757,부암동와플,4.3,21,제과점,서울특별시 종로구 부암동 254-1번지 지상1층,플레인이 담백하고 맛있었음. 날씨 좋은 봄날 산책하다 들러 먹으면 좋음.
5758,부암동와플,4.3,21,제과점,서울특별시 종로구 부암동 254-1번지 지상1층,새로 생긴 작은 가게인데 와플을 바로 구워주니 쫄깃하고 맛있어요

In [184]:
info['category'].value_counts()

category
제과점            63
카페             21
커피숍/커피 전문점      6
디저트 전문점         4
프랑스 제과점         2
케이크 전문점         2
독일 음식점          1
음식점             1
절인 햄 전문 음식점     1
Name: count, dtype: int64

In [186]:
info[info['category'].str.contains('음식점')]

          name  rating  review     category                 adress
43    더베이커스테이블     4.0    1287       독일 음식점      서울특별시 종로구 삼청로 126
78  두채 doochae     4.4     106          음식점    서울특별시 종로구 율곡로13가길 8
95    소금집델리 안국     4.3     553  절인 햄 전문 음식점  서울특별시 종로구 북촌로4길 19 1층

# 은평구-서대문구-마포구-성북구-종로구-중구-동대문구-강남구

In [343]:
import pandas as pd

In [344]:
# 파일 읽기
addr = '강남구'
aria = 'Gangnam'
info_df = pd.read_csv(f'./google_{aria}_in.csv')
review_df = pd.read_csv(f'./google_{aria}_re.csv')

In [345]:
info_df

,number,Store,Review_score,Review_counts,Category,Address
0,1,빠삐용빵,4.3,(4),제과점,서울특별시 강남구 도산대로24길 29
1,2,쁠로13,4.5,(114),제과점,서울특별시 강남구 도산대로8길 13
2,3,바게트 케이,4.3,(266),제과점,서울특별시 강남구 테헤란로34길 21-10
3,4,빵에잠봉,4.8,(4),커피숍/커피 전문점,서울특별시 강남구 논현동 111-36
4,5,빵빠르,4.0,(6),디저트 전문점,서울특별시 강남구 강남대로156길 32
...,...,...,...,...,...,...
114,116,라파티세리킴 도곡점,4.0,(4),제과점,서울특별시 강남구 도곡동 번지 1층 420-16
115,117,룰링핀 빵지브,정보없음,정보없음,카페,서울특별시 강남구 테헤란로78길 16
116,118,원더시티 뉴욕컵케이크,3.8,(15),제과점,서울특별시 강남구 논현동 강남대로 556 1층
117,119,파리바게뜨 개포행복,4.0,(87),제과점,서울특별시 강남구 개포동 172-11
118,120,뚜레쥬르카페대치점,3.9,(7),제과점,서울특별시 강남구 도곡로 446

In [346]:
review_df

,number,Store,Review_text,Time
0,1,빠삐용빵,"가격은 꽤 합리적이고, 이곳의 빵은 대부분 건강해 보입니다. 빵집 자체는 작으며 작...",2024-04-06 - 16:39:48
1,1,빠삐용빵,없는 메뉴도 많고\r\n분위기랑 공간 특이하고 빵도 낫배드인데\r\n불친절하고 뭔가...,2024-04-06 - 16:39:48
2,1,빠삐용빵,페이스트리!,2024-04-06 - 16:39:48
3,2,쁠로13,"크루와상, 롤링핀이 맛있는 집. 유명한 데는 이유가 있다🥳 두입에 쏙 들어가는 작은...",2024-04-06 - 16:41:35
4,2,쁠로13,맛도좋고 작지만 서비스도 좋아요,2024-04-06 - 16:41:35
...,...,...,...,...
5530,120,뚜레쥬르카페대치점,식빵사러 갔는데 카페이다 보니\r\n다른 지점보다 조금 넓은편이고\r\n알바생들이 ...,2024-04-06 - 19:23:44
5531,120,뚜레쥬르카페대치점,다양한 빵들과 연유바게트가 시간만되면 기다려짐,2024-04-06 - 19:23:44
5532,120,뚜레쥬르카페대치점,프랜차이즈의 경우 일반적이지만 해당 지역의 특성상 조금 더 비쌀 수도 있다고 생각합...,2024-04-06 - 19:23:44
5533,120,뚜레쥬르카페대치점,"대치동 학원거리, 버스정류소 앞에 있는 뚜레쥬르 카페 대치점입니다. 뚜레쥬르 옆에는...",2024-04-06 - 19:23:44
5534,120,뚜레쥬르카페대치점,빵맛이 좋아요.\r\n친절합니다.,2024-04-06 - 19:23:44

In [347]:
# 1. 정보없음 가게체크
info_df[info_df['Store'].str.contains("정보")]

Empty DataFrame
Columns: [number, Store, Review_score, Review_counts, Category, Address]
Index: []

In [348]:
# 2-1. 중복체크 시리즈에 불리언식을 적용했다.
value_counts = info_df['Store'].value_counts()
value_counts[value_counts >= 2]

Series([], Name: count, dtype: int64)

In [349]:
# 2-2. 중복체크 시리즈에 람다함수를 적용했다.
info_df['Store'].value_counts()[lambda x: x >= 2]

Series([], Name: count, dtype: int64)

In [350]:
# 2-3. 중복체크 데이터프레임
info_df[info_df['Store'].map(info_df['Store'].value_counts()) >= 2]

Empty DataFrame
Columns: [number, Store, Review_score, Review_counts, Category, Address]
Index: []

In [351]:
# 2-4. 중복체크 데이터프레임
info_df.groupby('Store').filter(lambda x: len(x) >= 2)

Empty DataFrame
Columns: [number, Store, Review_score, Review_counts, Category, Address]
Index: []

In [342]:
# 3. 중복되는 가게별 리뷰가 있니?
review_df.groupby(['Store', 'Review_text']).filter(lambda x: len(x) >= 2)

Empty DataFrame
Columns: [number, Store, Review_text, Time]
Index: []

# 시작

In [352]:
# 1. 중복된 행 제거, 리뷰는 타임을 제외해야한다.
cleaned_info = info_df.drop_duplicates(subset=['Store', 'Review_counts', 'Address'], keep='first')
cleaned_review = review_df.drop_duplicates(subset=['Store', 'Review_text'], keep='first')

In [353]:
cleaned_info  # 6개의 가게가 빠졌다. 나머지 3개는 주소가 다르다.

,number,Store,Review_score,Review_counts,Category,Address
0,1,빠삐용빵,4.3,(4),제과점,서울특별시 강남구 도산대로24길 29
1,2,쁠로13,4.5,(114),제과점,서울특별시 강남구 도산대로8길 13
2,3,바게트 케이,4.3,(266),제과점,서울특별시 강남구 테헤란로34길 21-10
3,4,빵에잠봉,4.8,(4),커피숍/커피 전문점,서울특별시 강남구 논현동 111-36
4,5,빵빠르,4.0,(6),디저트 전문점,서울특별시 강남구 강남대로156길 32
...,...,...,...,...,...,...
114,116,라파티세리킴 도곡점,4.0,(4),제과점,서울특별시 강남구 도곡동 번지 1층 420-16
115,117,룰링핀 빵지브,정보없음,정보없음,카페,서울특별시 강남구 테헤란로78길 16
116,118,원더시티 뉴욕컵케이크,3.8,(15),제과점,서울특별시 강남구 논현동 강남대로 556 1층
117,119,파리바게뜨 개포행복,4.0,(87),제과점,서울특별시 강남구 개포동 172-11
118,120,뚜레쥬르카페대치점,3.9,(7),제과점,서울특별시 강남구 도곡로 446

In [354]:
# 음식점 제거, 빵집이 섞여있다.
cleaned_info[cleaned_info['Category'].str.contains('음식')]

Empty DataFrame
Columns: [number, Store, Review_score, Review_counts, Category, Address]
Index: []

In [307]:
# 진짜 빵집인지 확인하는 방법.
cleaned_review[cleaned_review['Store'].str.contains('신설동 계란빵')]

Empty DataFrame
Columns: [number, Store, Review_text, Time]
Index: []

In [303]:
# [주의] 인덱스로 삭제
cleaned_info = cleaned_info.drop(89)

In [355]:
# 프랜차이즈 제거
# 투썸, 이디야, 디저트39, 엔제리너스, 컴포즈, 공차, 풀바셋: 나는 없다.
con1 = cleaned_info['Store'].str.contains('파리바게')
con2 = cleaned_info['Store'].str.contains('메가커피')
con3 = cleaned_info['Store'].str.contains('뚜레쥬르')
con4 = cleaned_info['Store'].str.contains('스타벅스')
con5 = cleaned_info['Store'].str.contains('커핀그루나루')
con6 = cleaned_info['Store'].str.contains('던킨')
con7 = cleaned_info['Store'].str.contains('빽다방')
con8 = cleaned_info['Store'].str.contains('할리스')

cleaned_info = cleaned_info.loc[~con1&~con2&~con3&~con4&~con5&~con6&~con7&~con8]

In [356]:
cleaned_info

,number,Store,Review_score,Review_counts,Category,Address
0,1,빠삐용빵,4.3,(4),제과점,서울특별시 강남구 도산대로24길 29
1,2,쁠로13,4.5,(114),제과점,서울특별시 강남구 도산대로8길 13
2,3,바게트 케이,4.3,(266),제과점,서울특별시 강남구 테헤란로34길 21-10
3,4,빵에잠봉,4.8,(4),커피숍/커피 전문점,서울특별시 강남구 논현동 111-36
4,5,빵빠르,4.0,(6),디저트 전문점,서울특별시 강남구 강남대로156길 32
...,...,...,...,...,...,...
108,110,곤트란 쉐리에 선릉점,4.5,(2),제과점,서울특별시 강남구 역삼동 707-27
113,115,곤트란쉐리에 개포점,4.2,(17),제과점,"서울특별시 강남구 삼성로 11 상가 지하 1층 B105, 106호 디에이치아너힐즈"
114,116,라파티세리킴 도곡점,4.0,(4),제과점,서울특별시 강남구 도곡동 번지 1층 420-16
115,117,룰링핀 빵지브,정보없음,정보없음,카페,서울특별시 강남구 테헤란로78길 16
116,118,원더시티 뉴욕컵케이크,3.8,(15),제과점,서울특별시 강남구 논현동 강남대로 556 1층

In [357]:
cleaned_review  # 1차 중복 제거만 한 상태, 나중에 가게명을 제거하고 크로스 시킨 다음 number 재부여

,number,Store,Review_text,Time
0,1,빠삐용빵,"가격은 꽤 합리적이고, 이곳의 빵은 대부분 건강해 보입니다. 빵집 자체는 작으며 작...",2024-04-06 - 16:39:48
1,1,빠삐용빵,없는 메뉴도 많고\r\n분위기랑 공간 특이하고 빵도 낫배드인데\r\n불친절하고 뭔가...,2024-04-06 - 16:39:48
2,1,빠삐용빵,페이스트리!,2024-04-06 - 16:39:48
3,2,쁠로13,"크루와상, 롤링핀이 맛있는 집. 유명한 데는 이유가 있다🥳 두입에 쏙 들어가는 작은...",2024-04-06 - 16:41:35
4,2,쁠로13,맛도좋고 작지만 서비스도 좋아요,2024-04-06 - 16:41:35
...,...,...,...,...
5530,120,뚜레쥬르카페대치점,식빵사러 갔는데 카페이다 보니\r\n다른 지점보다 조금 넓은편이고\r\n알바생들이 ...,2024-04-06 - 19:23:44
5531,120,뚜레쥬르카페대치점,다양한 빵들과 연유바게트가 시간만되면 기다려짐,2024-04-06 - 19:23:44
5532,120,뚜레쥬르카페대치점,프랜차이즈의 경우 일반적이지만 해당 지역의 특성상 조금 더 비쌀 수도 있다고 생각합...,2024-04-06 - 19:23:44
5533,120,뚜레쥬르카페대치점,"대치동 학원거리, 버스정류소 앞에 있는 뚜레쥬르 카페 대치점입니다. 뚜레쥬르 옆에는...",2024-04-06 - 19:23:44
5534,120,뚜레쥬르카페대치점,빵맛이 좋아요.\r\n친절합니다.,2024-04-06 - 19:23:44

# 없을 수도

In [358]:
# 중복된 가게명, but 주소가 다르다.
cleaned_info['Store'].value_counts()[lambda x: x >= 2]

Series([], Name: count, dtype: int64)

In [359]:
# 중복된 가게명, but 주소가 다르다.
cleaned_info.groupby('Store').filter(lambda x: len(x) >= 2)

Empty DataFrame
Columns: [number, Store, Review_score, Review_counts, Category, Address]
Index: []

In [82]:
# 인덱스로!! 가게명 재지정
cleaned_info.loc[62, 'Store'] = '누아네 신수동점'
cleaned_info.loc[71, 'Store'] = '누아네 대흥동점'

In [ ]:
# 솔트24 리뷰수 하나로 합치기
# cleaned_info.loc[3] = ['4', '솔트24 북촌점', '4.5', '(204)', '제과점', '서울특별시 종로구 율곡로3길 75']
# cleaned_info =cleaned_info.drop(36)

# 그럼 여기

In [362]:
# 해당구를 포함하지 않는 가게 삭제
cleaned_info[~cleaned_info['Address'].str.contains(f'{addr}')]

     number    Store Review_score Review_counts Category               Address
64       65     자연식빵         정보없음          정보없음      제과점    서울특별시 서초구 강남대로 396
100     102  타르틴베이커리          4.1         (755)      제과점  서울특별시 용산구 한남대로18길 22

In [361]:
# 주소 없으면 추가
cleaned_info.loc[106, 'Address'] = '서울 강남구 선릉로126길 6'

In [363]:
# 해당구를 포함하지 않는 가게 삭제
con1 = ~cleaned_info['Address'].str.contains(f'{addr}')
cleaned_info = cleaned_info.drop(cleaned_info[con1].index)

In [364]:
cleaned_info

,number,Store,Review_score,Review_counts,Category,Address
0,1,빠삐용빵,4.3,(4),제과점,서울특별시 강남구 도산대로24길 29
1,2,쁠로13,4.5,(114),제과점,서울특별시 강남구 도산대로8길 13
2,3,바게트 케이,4.3,(266),제과점,서울특별시 강남구 테헤란로34길 21-10
3,4,빵에잠봉,4.8,(4),커피숍/커피 전문점,서울특별시 강남구 논현동 111-36
4,5,빵빠르,4.0,(6),디저트 전문점,서울특별시 강남구 강남대로156길 32
...,...,...,...,...,...,...
108,110,곤트란 쉐리에 선릉점,4.5,(2),제과점,서울특별시 강남구 역삼동 707-27
113,115,곤트란쉐리에 개포점,4.2,(17),제과점,"서울특별시 강남구 삼성로 11 상가 지하 1층 B105, 106호 디에이치아너힐즈"
114,116,라파티세리킴 도곡점,4.0,(4),제과점,서울특별시 강남구 도곡동 번지 1층 420-16
115,117,룰링핀 빵지브,정보없음,정보없음,카페,서울특별시 강남구 테헤란로78길 16
116,118,원더시티 뉴욕컵케이크,3.8,(15),제과점,서울특별시 강남구 논현동 강남대로 556 1층

In [365]:
# inner merge하면 사라지는 데이터 행들이니 신경쓰지 않아도 된다.
cleaned_info[cleaned_info['Review_score'].str.contains('정보')]

,number,Store,Review_score,Review_counts,Category,Address
17,18,Super빵,정보없음,정보없음,제과점,서울특별시 강남구 도산대로1길 36
27,28,빵어니스타,정보없음,정보없음,제과점,서울특별시 강남구 압구정동 494번지 갤러리아백화점명품관웨스트
83,85,빵이가득한집,정보없음,정보없음,제과점,논현동 163-2번지 강남구 서울특별시 KR
87,89,빵준서 갤러리아 명품관,정보없음,정보없음,제과점,서울특별시 강남구 압구정로 343 갤러리아 명품관 WEST B1F
115,117,룰링핀 빵지브,정보없음,정보없음,카페,서울특별시 강남구 테헤란로78길 16

In [366]:
# 변경 전 이름은 제거
cross_review = cleaned_review.drop('Store', axis=1)

In [367]:
cross_review

,number,Review_text,Time
0,1,"가격은 꽤 합리적이고, 이곳의 빵은 대부분 건강해 보입니다. 빵집 자체는 작으며 작...",2024-04-06 - 16:39:48
1,1,없는 메뉴도 많고\r\n분위기랑 공간 특이하고 빵도 낫배드인데\r\n불친절하고 뭔가...,2024-04-06 - 16:39:48
2,1,페이스트리!,2024-04-06 - 16:39:48
3,2,"크루와상, 롤링핀이 맛있는 집. 유명한 데는 이유가 있다🥳 두입에 쏙 들어가는 작은...",2024-04-06 - 16:41:35
4,2,맛도좋고 작지만 서비스도 좋아요,2024-04-06 - 16:41:35
...,...,...,...
5530,120,식빵사러 갔는데 카페이다 보니\r\n다른 지점보다 조금 넓은편이고\r\n알바생들이 ...,2024-04-06 - 19:23:44
5531,120,다양한 빵들과 연유바게트가 시간만되면 기다려짐,2024-04-06 - 19:23:44
5532,120,프랜차이즈의 경우 일반적이지만 해당 지역의 특성상 조금 더 비쌀 수도 있다고 생각합...,2024-04-06 - 19:23:44
5533,120,"대치동 학원거리, 버스정류소 앞에 있는 뚜레쥬르 카페 대치점입니다. 뚜레쥬르 옆에는...",2024-04-06 - 19:23:44
5534,120,빵맛이 좋아요.\r\n친절합니다.,2024-04-06 - 19:23:44

In [369]:
# 데이터행 개수 확인
merged_df = pd.merge(cleaned_info, cross_review, on=["number"], how="inner")
merged_df

,number,Store,Review_score,Review_counts,Category,Address,Review_text,Time
0,1,빠삐용빵,4.3,(4),제과점,서울특별시 강남구 도산대로24길 29,"가격은 꽤 합리적이고, 이곳의 빵은 대부분 건강해 보입니다. 빵집 자체는 작으며 작...",2024-04-06 - 16:39:48
1,1,빠삐용빵,4.3,(4),제과점,서울특별시 강남구 도산대로24길 29,없는 메뉴도 많고\r\n분위기랑 공간 특이하고 빵도 낫배드인데\r\n불친절하고 뭔가...,2024-04-06 - 16:39:48
2,1,빠삐용빵,4.3,(4),제과점,서울특별시 강남구 도산대로24길 29,페이스트리!,2024-04-06 - 16:39:48
3,2,쁠로13,4.5,(114),제과점,서울특별시 강남구 도산대로8길 13,"크루와상, 롤링핀이 맛있는 집. 유명한 데는 이유가 있다🥳 두입에 쏙 들어가는 작은...",2024-04-06 - 16:41:35
4,2,쁠로13,4.5,(114),제과점,서울특별시 강남구 도산대로8길 13,맛도좋고 작지만 서비스도 좋아요,2024-04-06 - 16:41:35
...,...,...,...,...,...,...,...,...
4257,118,원더시티 뉴욕컵케이크,3.8,(15),제과점,서울특별시 강남구 논현동 강남대로 556 1층,가격이 싼편은 아닌데 맛은 평타임. 초콜릿맛이 싼티가 좀 나긴하지만 레터링케이크 치...,2024-04-06 - 19:22:05
4258,118,원더시티 뉴욕컵케이크,3.8,(15),제과점,서울특별시 강남구 논현동 강남대로 556 1층,- 좋아하는 스타일은 아니지만 컵케잌 귀엽고 가격도 괜찮은 편\r\n- 커스텀 케이...,2024-04-06 - 19:22:05
4259,118,원더시티 뉴욕컵케이크,3.8,(15),제과점,서울특별시 강남구 논현동 강남대로 556 1층,생일 케이크를 원하는대로 커스텀 할 수 있고 미리 주문할수 있다.\r\n그리고 케잌...,2024-04-06 - 19:22:05
4260,118,원더시티 뉴욕컵케이크,3.8,(15),제과점,서울특별시 강남구 논현동 강남대로 556 1층,불행하게도 컵케이크는 가격이 비싸고 작습니다. 카페 자체에는 플러그 포인트가 없기 ...,2024-04-06 - 19:22:05
4261,118,원더시티 뉴욕컵케이크,3.8,(15),제과점,서울특별시 강남구 논현동 강남대로 556 1층,홍대점이 후 강남에도. 논현역에 있어요~ 한남점은 현대카드 뮤직 라이브러리 안에 차...,2024-04-06 - 19:22:05

In [370]:
# 가게명 기준으로 고유 번호 부여
merged_df['Number'] = pd.factorize(merged_df['Store'])[0] + 1

In [371]:
# 리뷰(2)라고 떠도 but 텍스트 없으면 안 뜬다.
merged_df

,number,Store,Review_score,Review_counts,Category,Address,Review_text,Time,Number
0,1,빠삐용빵,4.3,(4),제과점,서울특별시 강남구 도산대로24길 29,"가격은 꽤 합리적이고, 이곳의 빵은 대부분 건강해 보입니다. 빵집 자체는 작으며 작...",2024-04-06 - 16:39:48,1
1,1,빠삐용빵,4.3,(4),제과점,서울특별시 강남구 도산대로24길 29,없는 메뉴도 많고\r\n분위기랑 공간 특이하고 빵도 낫배드인데\r\n불친절하고 뭔가...,2024-04-06 - 16:39:48,1
2,1,빠삐용빵,4.3,(4),제과점,서울특별시 강남구 도산대로24길 29,페이스트리!,2024-04-06 - 16:39:48,1
3,2,쁠로13,4.5,(114),제과점,서울특별시 강남구 도산대로8길 13,"크루와상, 롤링핀이 맛있는 집. 유명한 데는 이유가 있다🥳 두입에 쏙 들어가는 작은...",2024-04-06 - 16:41:35,2
4,2,쁠로13,4.5,(114),제과점,서울특별시 강남구 도산대로8길 13,맛도좋고 작지만 서비스도 좋아요,2024-04-06 - 16:41:35,2
...,...,...,...,...,...,...,...,...,...
4257,118,원더시티 뉴욕컵케이크,3.8,(15),제과점,서울특별시 강남구 논현동 강남대로 556 1층,가격이 싼편은 아닌데 맛은 평타임. 초콜릿맛이 싼티가 좀 나긴하지만 레터링케이크 치...,2024-04-06 - 19:22:05,82
4258,118,원더시티 뉴욕컵케이크,3.8,(15),제과점,서울특별시 강남구 논현동 강남대로 556 1층,- 좋아하는 스타일은 아니지만 컵케잌 귀엽고 가격도 괜찮은 편\r\n- 커스텀 케이...,2024-04-06 - 19:22:05,82
4259,118,원더시티 뉴욕컵케이크,3.8,(15),제과점,서울특별시 강남구 논현동 강남대로 556 1층,생일 케이크를 원하는대로 커스텀 할 수 있고 미리 주문할수 있다.\r\n그리고 케잌...,2024-04-06 - 19:22:05,82
4260,118,원더시티 뉴욕컵케이크,3.8,(15),제과점,서울특별시 강남구 논현동 강남대로 556 1층,불행하게도 컵케이크는 가격이 비싸고 작습니다. 카페 자체에는 플러그 포인트가 없기 ...,2024-04-06 - 19:22:05,82
4261,118,원더시티 뉴욕컵케이크,3.8,(15),제과점,서울특별시 강남구 논현동 강남대로 556 1층,홍대점이 후 강남에도. 논현역에 있어요~ 한남점은 현대카드 뮤직 라이브러리 안에 차...,2024-04-06 - 19:22:05,82

In [372]:
merged_df['Platform'] = 'Google'
merged_df['Addr'] = f'서울 {addr}'
merged_df['ID'] = '정보없음'
merged_df['Date'] = '정보없음'

In [116]:
# 컬럼 이름 변경
# merged_df = merged_df.rename(columns={'number': 'Number'})

In [373]:
merged_df = merged_df[['Platform', 'Number', 'Store', 'Address', 'Addr', 'Review_score', 'Review_counts', 'ID', 'Date', 'Review_text', 'Time']]
merged_df

,Platform,Number,Store,Address,Addr,Review_score,Review_counts,ID,Date,Review_text,Time
0,Google,1,빠삐용빵,서울특별시 강남구 도산대로24길 29,서울 강남구,4.3,(4),정보없음,정보없음,"가격은 꽤 합리적이고, 이곳의 빵은 대부분 건강해 보입니다. 빵집 자체는 작으며 작...",2024-04-06 - 16:39:48
1,Google,1,빠삐용빵,서울특별시 강남구 도산대로24길 29,서울 강남구,4.3,(4),정보없음,정보없음,없는 메뉴도 많고\r\n분위기랑 공간 특이하고 빵도 낫배드인데\r\n불친절하고 뭔가...,2024-04-06 - 16:39:48
2,Google,1,빠삐용빵,서울특별시 강남구 도산대로24길 29,서울 강남구,4.3,(4),정보없음,정보없음,페이스트리!,2024-04-06 - 16:39:48
3,Google,2,쁠로13,서울특별시 강남구 도산대로8길 13,서울 강남구,4.5,(114),정보없음,정보없음,"크루와상, 롤링핀이 맛있는 집. 유명한 데는 이유가 있다🥳 두입에 쏙 들어가는 작은...",2024-04-06 - 16:41:35
4,Google,2,쁠로13,서울특별시 강남구 도산대로8길 13,서울 강남구,4.5,(114),정보없음,정보없음,맛도좋고 작지만 서비스도 좋아요,2024-04-06 - 16:41:35
...,...,...,...,...,...,...,...,...,...,...,...
4257,Google,82,원더시티 뉴욕컵케이크,서울특별시 강남구 논현동 강남대로 556 1층,서울 강남구,3.8,(15),정보없음,정보없음,가격이 싼편은 아닌데 맛은 평타임. 초콜릿맛이 싼티가 좀 나긴하지만 레터링케이크 치...,2024-04-06 - 19:22:05
4258,Google,82,원더시티 뉴욕컵케이크,서울특별시 강남구 논현동 강남대로 556 1층,서울 강남구,3.8,(15),정보없음,정보없음,- 좋아하는 스타일은 아니지만 컵케잌 귀엽고 가격도 괜찮은 편\r\n- 커스텀 케이...,2024-04-06 - 19:22:05
4259,Google,82,원더시티 뉴욕컵케이크,서울특별시 강남구 논현동 강남대로 556 1층,서울 강남구,3.8,(15),정보없음,정보없음,생일 케이크를 원하는대로 커스텀 할 수 있고 미리 주문할수 있다.\r\n그리고 케잌...,2024-04-06 - 19:22:05
4260,Google,82,원더시티 뉴욕컵케이크,서울특별시 강남구 논현동 강남대로 556 1층,서울 강남구,3.8,(15),정보없음,정보없음,불행하게도 컵케이크는 가격이 비싸고 작습니다. 카페 자체에는 플러그 포인트가 없기 ...,2024-04-06 - 19:22:05
4261,Google,82,원더시티 뉴욕컵케이크,서울특별시 강남구 논현동 강남대로 556 1층,서울 강남구,3.8,(15),정보없음,정보없음,홍대점이 후 강남에도. 논현역에 있어요~ 한남점은 현대카드 뮤직 라이브러리 안에 차...,2024-04-06 - 19:22:05

In [374]:
# 최종 데이터프레임 저장
cleaned_info.to_csv(f'cleaned_{aria}.csv', index=False)
merged_df.to_csv(f'google_{aria}.csv', index=False)

In [ ]:
# 최종 데이터 행
은평구 877
서대문구 2538
마포구 4071
성북구 2207
종로구 4942
중구 3527
동대문구 666
강남구 4262
= 약 23,090개

# 2차 전처리 코드

In [2]:
import pandas as pd
info_1 = pd.read_csv('./google_Enpyeong.csv')
info_2 = pd.read_csv('./google_Seodaemun.csv')
info_3 = pd.read_csv('./google_Mapo.csv')
info_4 = pd.read_csv('./google_Seongbuk.csv')
info_5 = pd.read_csv('./google_Jongro.csv')
info_6 = pd.read_csv('./google_Jung.csv')
info_7 = pd.read_csv('./google_Dongdaemun.csv')
info_8 = pd.read_csv('./google_Gangnam.csv')

In [7]:
# 병합
info = pd.concat([info_1,info_2,info_3,info_4,info_5,info_6,info_7,info_8], axis=0)

In [9]:
# 괄호/콤마 제거
info['Review_counts'] = info['Review_counts'].str.replace('(','').str.replace(')','').str.replace(',','')

In [11]:
# 자료형 변환
info['Review_score'] = info['Review_score'].astype(float)
info['Review_counts'] = info['Review_counts'].astype(int)

In [17]:
# 띄어쓰기, 개행 제거
info['Review_text'] = info['Review_text'].str.replace('\r\n', " ")
info['Review_text'] = info['Review_text'].str.replace('\n', " ")

In [21]:
# 재확인
info[info['Review_text'].str.contains('\n')]

Empty DataFrame
Columns: [Platform, Number, Store, Address, Addr, Review_score, Review_counts, ID, Date, Review_text, Time]
Index: []

In [18]:
# 가게명 공백 없애기
import pandas as pd
info = pd.read_csv('./google_bread.csv')
info['Store'] = info['Store'].str.replace(' ', '')
info

,Platform,Number,Store,Address,Addr,Review_score,Review_counts,ID,Date,Review_text,Time
0,Google,1,도돌이표,서울특별시 은평구 진관3로 70 823동 상가 106호,서울 은평구,4.7,14,정보없음,정보없음,맛있어요.,2024-04-07 - 08:25:08
1,Google,1,도돌이표,서울특별시 은평구 진관3로 70 823동 상가 106호,서울 은평구,4.7,14,정보없음,정보없음,은평뉴타운 최고의 빵집. 성수동빵집/이촌동빵집 저리가라입니다. 일단 다 맛있어요,2024-04-07 - 08:25:08
2,Google,1,도돌이표,서울특별시 은평구 진관3로 70 823동 상가 106호,서울 은평구,4.7,14,정보없음,정보없음,제가 좋아하는 빵집이에요~^^오늘은 가르치는 학생들에게 크리스마스 선물로 미리...,2024-04-07 - 08:25:08
3,Google,1,도돌이표,서울특별시 은평구 진관3로 70 823동 상가 106호,서울 은평구,4.7,14,정보없음,정보없음,가게 크기랑 내부가 귀엽다. 빵 종류는 유럽+한국 퓨전 스타일. 다양하고 괜찮다. ...,2024-04-07 - 08:25:08
4,Google,1,도돌이표,서울특별시 은평구 진관3로 70 823동 상가 106호,서울 은평구,4.7,14,정보없음,정보없음,"가격은 주변에 비해 다소 높지만, 매일 신선한 건강하고 맛있는 빵을 먹을 수 있습니다.",2024-04-07 - 08:25:08
...,...,...,...,...,...,...,...,...,...,...,...
23085,Google,82,원더시티뉴욕컵케이크,서울특별시 강남구 논현동 강남대로 556 1층,서울 강남구,3.8,15,정보없음,정보없음,가격이 싼편은 아닌데 맛은 평타임. 초콜릿맛이 싼티가 좀 나긴하지만 레터링케이크 치...,2024-04-06 - 19:22:05
23086,Google,82,원더시티뉴욕컵케이크,서울특별시 강남구 논현동 강남대로 556 1층,서울 강남구,3.8,15,정보없음,정보없음,- 좋아하는 스타일은 아니지만 컵케잌 귀엽고 가격도 괜찮은 편 - 커스텀 케이크도 ...,2024-04-06 - 19:22:05
23087,Google,82,원더시티뉴욕컵케이크,서울특별시 강남구 논현동 강남대로 556 1층,서울 강남구,3.8,15,정보없음,정보없음,생일 케이크를 원하는대로 커스텀 할 수 있고 미리 주문할수 있다. 그리고 케잌이 아...,2024-04-06 - 19:22:05
23088,Google,82,원더시티뉴욕컵케이크,서울특별시 강남구 논현동 강남대로 556 1층,서울 강남구,3.8,15,정보없음,정보없음,불행하게도 컵케이크는 가격이 비싸고 작습니다. 카페 자체에는 플러그 포인트가 없기 ...,2024-04-06 - 19:22:05
23089,Google,82,원더시티뉴욕컵케이크,서울특별시 강남구 논현동 강남대로 556 1층,서울 강남구,3.8,15,정보없음,정보없음,홍대점이 후 강남에도. 논현역에 있어요~ 한남점은 현대카드 뮤직 라이브러리 안에 차...,2024-04-06 - 19:22:05

In [19]:
# 저장
info.to_csv('google_bread.csv', index=False)

# 참고코드

In [ ]:
# 1. 데이터 편집하기
info_df.loc[57] = ['파리바게트 서교점', '3.9', '126', '제과점', '서울특별시 마포구 월드컵북로 34']
# 2. 행 삭제하기
info_df = info_df.drop(107, axis=0)
# 3. 인덱스 리셋하며 새로 만들지 말기
info_df = info_df.reset_index(drop=True)
# 4. 파일 읽기
info_df = pd.read_csv('./google_Dongdaemun_in.csv')
review_df = pd.read_csv('./google_Dongdaemun_re.csv')
# 5. 정보없음 대체값
info_df['Store'] = info_df['Store'].str.replace('정보없음', '파리바게뜨 서교점')
info_df['Address'] = info_df['Address'].str.replace('정보없음', '서울특별시 마포구 월드컵북로 34')
# 6. merge row counts =review_df row counts 개수체크 (inner, outer)
merged_df = pd.merge(info_df, review_df, on=["number"], how="outer")
merged_df
# 7. 저장코드
info_df.to_csv('google_Enpyeong_in.csv', index=False)
review_df.to_csv('google_Enpyeong_re.csv', index=False)
merged_df.to_csv('google_Enpyeong.csv', index=False)

In [ ]:
# 1. 조건별 특정 인덱스의 리뷰 전문
review_df[review_df['Store'].str.contains('몽핀')].loc[128, 'Review_text']
# 2. 인덱스별 리뷰 전문
review_df['Review_text'][0]
# 3. 조건별 리뷰내용 전문보기 > CSV파일 있으면 해당 파일로 확인한다.
con1 = (review_df['Store'] == '파네트')
con2 = (review_df['Review_text'].str.contains('오다가다'))
print(review_df[con1&con2]['Review_text'][178])